### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sharathmatada** [mayataka/robotoc#132]
Hi I built the robotoc code but when I try to import it I get the following image

>>> import robotoc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/robotoc/__init__.py", line 1, in <module>
    from .robot import *
  File "/usr/local/lib/python3.10/site-packages/robotoc/robot/__init__.py", line 1, in <module>
    from .contact_status import *
ModuleNotFoundError: No module named 'robotoc.robot.contact_status'
>>> import math
>>> import robotoc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/robotoc/__init__.py", line 1, in <module>
    from .robot import *
  File "/usr/local/lib/python3.10/site-packages/robotoc/robot/__init__.py", line 1, in <module>
    from .contact_status import *
ModuleNotFoundError: No module named 'robotoc.robot.contact_status'

Any idea what the issue is?

**Comment by mayataka** [comment]
Hi @sharathmatada,
This is resolved by #133.
Could you try the latest version?
